[env:cardputer-adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino
build_flags =
    -Os
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer
    z3t0/IRremote@^4.4.1
    h2zero/NimBLE-Arduino@^2.3.0
