#!/usr/bin/env python3
"""Render a TTF into a VLW (Processing smooth font) for LovyanGFX/M5GFX and emit a C header.

usage: make_vlw.py <font.ttf> <pixel size> <symbol name> <out.h> [--png preview.png]
"""
import struct
import sys

from PIL import Image, ImageDraw, ImageFont

CHARS = (
    [chr(c) for c in range(0x20, 0x7F)]
    + [chr(c) for c in range(0x410, 0x450)]  # А-я
    + list("ЁёЇїІіЄєҐґЎў")
    + list("«»—–…„“”‘’№°·•×±\u00A0")
)


def build(ttf, size):
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    for ch in sorted(set(CHARS), key=ord):
        advance = round(font.getlength(ch))
        if ch in (" ", " "):
            glyphs.append((ord(ch), 0, 0, advance, 0, 0, b""))
            continue
        mask, (ox, oy) = font.getmask2(ch, mode="L", anchor="ls")
        w, h = mask.size
        if w == 0 or h == 0:
            continue  # glyph missing from the font
        data = bytes(mask)
        glyphs.append((ord(ch), h, w, advance, -oy, ox, data))
    return ascent, descent, glyphs


def to_vlw(size, ascent, descent, glyphs):
    out = bytearray(struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent))
    for code, h, w, adv, top, left, _ in glyphs:
        out += struct.pack(">7i", code, h, w, adv, top, left, 0)
    for *_, data in glyphs:
        out += data
    return bytes(out)


def preview(vlw, text, path):
    """Decode the VLW back (the way LovyanGFX does) and draw text, to check the file visually."""
    count, _, _, _, ascent, descent = struct.unpack(">6i", vlw[:24])
    metrics, ptr = {}, 24 + count * 28
    for i in range(count):
        code, h, w, adv, top, left, _ = struct.unpack(">7i", vlw[24 + i * 28: 52 + i * 28])
        metrics[code] = (h, w, adv, top, left, ptr)
        ptr += w * h
    img = Image.new("L", (sum(metrics.get(ord(c), (0, 0, 10))[2] for c in text) + 20, ascent + descent + 20), 0)
    x, base = 10, 10 + ascent
    for c in text:
        if ord(c) not in metrics:
            x += 10
            continue
        h, w, adv, top, left, p = metrics[ord(c)]
        if w and h:
            g = Image.frombytes("L", (w, h), vlw[p: p + w * h])
            img.paste(g, (x + left, base - top), g)
        x += adv
    img.save(path)


def main():
    ttf, size, name, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    ascent, descent, glyphs = build(ttf, size)
    vlw = to_vlw(size, ascent, descent, glyphs)
    with open(out, "w") as f:
        f.write(f"// Generated by tools/make_vlw.py from {ttf.split('/')[-1]} ({size}px, OFL). Do not edit.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"const uint8_t {name}[{len(vlw)}] = {{\n")
        for i in range(0, len(vlw), 24):
            f.write("  " + ",".join(str(b) for b in vlw[i: i + 24]) + ",\n")
        f.write("};\n")
    print(f"{name}: {len(glyphs)} glyphs, {len(vlw)} bytes")
    if "--png" in sys.argv:
        preview(vlw, "Съешь же ещё, «ёж» — 123 Hello!", sys.argv[sys.argv.index("--png") + 1])


if __name__ == "__main__":
    main()
